// @ts-ignore
import Head from 'next/head';
// @ts-ignore
import type { NextPage } from 'next';
import Header from '../components/Header';
import requests from '../utils/request';
import Banner from '../components/Banner';
import { Movie } from '../types';
// @ts-ignore
import Row from '../components/Row';

interface props {
  NetflixOriginals: Movie[];
  Trending: Movie[];
  TopRated: Movie[];
  ActionMovies: Movie[];
  ComedyMovies: Movie[];
  HorrorMovies: Movie[];
  RomanceMovies: Movie[];
  Documentaries: Movie[];
}

const Home: NextPage = ({
  NetflixOriginals,
  Trending,
  TopRated,
  ActionMovies,
  ComedyMovies,
  HorrorMovies,
  RomanceMovies,
  Documentaries,
}: props) => {
  return (
    <div className="relative h-screen w-screen  bg-gradient-to-b from-gray-900/10 to-[#010511] lg:h-[140vh]">
      <Head>
        <title> netflix </title>{' '}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* <Nav /> */}
      <main className="relative pb-24 pl-4 lg:space-y-24 lg:pl-16 ">
        <Banner NetflixOriginals={NetflixOriginals} />
        <section className="-ml-6 md:-ml-16 ">
          <Row title="Trending" movies={Trending} />
          <Row title="TopRated" movies={TopRated} />
          <Row title="ActionMovies" movies={ActionMovies} />
          <Row title="ComedyMovies" movies={ComedyMovies} />
          <Row title="HorrorMovies" movies={HorrorMovies} />
          <Row title="RomanceMovies" movies={RomanceMovies} />
          <Row title="Documentaries" movies={Documentaries} />
        </section>
      </main>
      {/* modal */}
    </div>
  );
};
export default Home;

export const getServerSideProps = async () => {
  const [
    NetflixOriginals,
    Trending,
    TopRated,
    ActionMovies,
    ComedyMovies,
    HorrorMovies,
    RomanceMovies,
    Documentaries,
  ] = await Promise.all([
    fetch(requests.fetchNetflixOriginals).then((res) => res.json()),
    fetch(requests.fetchTrending).then((res) => res.json()),
    fetch(requests.fetchTopRated).then((res) => res.json()),
    fetch(requests.fetchActionMovies).then((res) => res.json()),
    fetch(requests.fetchComedyMovies).then((res) => res.json()),
    fetch(requests.fetchHorrorMovies).then((res) => res.json()),
    fetch(requests.fetchRomanceMovies).then((res) => res.json()),
    fetch(requests.fetchDocumentaries).then((res) => res.json()),
  ]);
  return {
    props: {
      NetflixOriginals: NetflixOriginals.results,
      Trending: Trending.results,
      TopRated: TopRated.results,
      ActionMovies: ActionMovies.results,
      ComedyMovies: ComedyMovies.results,
      HorrorMovies: HorrorMovies.results,
      RomanceMovies: RomanceMovies.results,
      Documentaries: Documentaries.results,
    },
  };
};
