import Head from 'next/head';
import type { NextPage } from 'next';
import Header from '../components/Header';
import requests from '../utils/request';
const Home: NextPage = ({
  NetflixOriginals,
  Trending,
  TopRated,
  ActionMovies,
  ComedyMovies,
  HorrorMovies,
  RomanceMovies,
  Documentaries,
}) => {
  console.log(Trending);
  return (
    <div className="relative  bg-gradient-to-b from-gray-900/10 to-[#010511] lg:h-[140vh]">
      <Head>
        <title> netflix </title>{' '}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        {/* row */}
        {/* row */}
        {/* row */}
        {/* row */}
        {/* row */}
        {/* row */}
      </main>
      {/* modal */}
    </div>
  );
};
export default Home;

export const getServerSideProps = async () => {
  const [
    NetflixOriginals,
    Trending,
    TopRated,
    ActionMovies,
    ComedyMovies,
    HorrorMovies,
    RomanceMovies,
    Documentaries,
  ] = await Promise.all([
    fetch(requests.fetchNetflixOriginals).then((res) => res.json()),
    fetch(requests.fetchTrending).then((res) => res.json()),
    fetch(requests.fetchTopRated).then((res) => res.json()),
    fetch(requests.fetchActionMovies).then((res) => res.json()),
    fetch(requests.fetchComedyMovies).then((res) => res.json()),
    fetch(requests.fetchHorrorMovies).then((res) => res.json()),
    fetch(requests.fetchRomanceMovies).then((res) => res.json()),
    fetch(requests.fetchDocumentaries).then((res) => res.json()),
  ]);
  return {
    props: {
      NetflixOriginals: NetflixOriginals.results,
      Trending: Trending.results,
      TopRated: TopRated.results,
      ActionMovies: ActionMovies.results,
      ComedyMovies: ComedyMovies.results,
      HorrorMovies: HorrorMovies.results,
      RomanceMovies: RomanceMovies.results,
      Documentaries: Documentaries.results,
    },
  };
};
